apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: go-webapp

resources:
  - ../../base

images:
  - name: app-image
    newName: docker.io/saitejabodapati925/go-webapp
    newTag: latest
